### ISSUE TITLE
Application on UCI dataset

### ISSUE THREAD

**Issue by lilyuanjun** [hongyanz/Stackelberg-GAN#1]
Hi Hongyang, 

I have read your paper "Medical missing data imputation by Stackelberg GAN". Great paper!

May I ask do you have the tutorial for the application on UCI dataset as described in the paper?

Thank you!
Yuanjun

**Comment by hongyanz** [comment]
Hi Yuanjun,

Thanks for your interest in our work.

This Github repo is for another paper using Stackelberg GAN to generate images. Unfortunately, for the paper that you are referring to, I am unable to release the codes at this moment because of the copyright policy from Petuum. You can refer to the code in https://github.com/jsyoon0823/GAIN, which also uses GAN to impute missing data and which we adapt our code from.

Best,
Hongyang
